### ISSUE TITLE
Do not support background color parameters?

### ISSUE THREAD

**Issue by shanzemin** [brilam/remove-bg#11]
It doesn't seem to work？

**Comment by brilam** [comment]
Hi. Thanks for letting me know. This API wrapper hasn't been updated in awhile. I will update this sometime this week. I will let you know when it is fixed. :)

**Comment by shanzemin** [comment]
> Hi. Thanks for letting me know. This API wrapper hasn't been updated in awhile. I will update this sometime this week. I will let you know when it is fixed. :)

Thank you very much!

**Comment by brilam** [comment]
Sorry for the delay! I've looked into this. I just forgot to push the the changes to PyPI. The changes are available now if you install removebg from pip. Thanks for letting me know. :)
