### ISSUE TITLE
Format and other options

### ISSUE THREAD

**Issue by GrbavaCigla** [brilam/remove-bg#14]
Hi, i am looking for some features that API provides, but this library doesn't. Would you merge my pull request? Thanks.

**Comment by brilam** [comment]
Sure thing. Are you participating in Hacktoberfest by any chance? If so, I can label this with Hacktoberfest so you can get your free T-Shirt. :)

**Comment by GrbavaCigla** [comment]
Yes I am :). This would be my 3rd pr.

**Comment by GrbavaCigla** [comment]
Almost done. Only thing that is left is background image/color/url

**Comment by brilam** [comment]
Great work!
